{
	"tag":"unique_name",
	"globals":{
		"target":"10.10.10.4"
		},
	"portscan":{
		"modules/portscan/tcpcommon":{
			"name":"Module_SCAN_TCPCommon"
			}
	},
	"ports":{
		"22":{
			"modules/ssh/userenum":{
				"name":"Module_SSH_nmapenum",
				"userfile":"/usr/share/seclists/Usernames/top-usernames-shortlist.txt"
				}
			},
		"25":{
			"modules/smtp/nmap_enum":{
				"name":"Module_SMTP_nmapenum",
				"port":"25"
				},
			"modules/smtp/nmap_vuln":{
				"name":"Module_SMTP_nmapvuln",
				"port":"25"
				},
			"modules/smtp/smtpvrfy":{
				"name":"Module_SMTP_VRFY",
				"userfile":"/usr/share/seclists/Usernames/top-usernames-shortlist.txt"
				}
			},
		"53":{
			"modules/dns/dnsrecon":{
				"name":"Module_DNS_dnsrecon"
				}
			},
		"80":{
			"modules/http/dirsearch":{
				"name":"Module_HTTP_dirsearch",
				"secure":"False"
				},
			"modules/http/nikto":{
				"name":"Module_HTTP_nikto",
				"secure":"False"
				}
			},
		"443":{
			"modules/http/dirsearch":{
				"name":"Module_HTTP_dirsearch",
				"secure":"True"
				},
			"modules/http/nikto":{
				"name":"Module_HTTP_nikto",
				"secure":"True"
				}
		},
		"445":{
			"modules/smb/smbmap":{
				"name":"Module_SMB_smbmap"
				},
			"modules/smb/enum4linux":{
				"name":"Module_SMB_enum4linux"
				},
			"modules/smb/nbtscan":{
				"name":"Module_SMB_nbtscan"
				},
			"modules/smb/nmap_enum":{
				"name":"Module_SMB_nmapenum",
				"port":"445"
				},
			"modules/smb/nmap_vuln":{
				"name":"Module_SMB_nmapvuln",
				"port":"445"
				}
		}
	},
	"generic":{
		"modules/icmp/ping":{
			"name":"Module_ICMP_Ping"
			}
	}
}
