{
	"tag":"unique_name",
	"globals":{
		"target":"10.11.1.5,10.11.1.8"
		},
	"portscan":{
		"modules/portscan/tcpcommon":{
			"name":"Module_SCAN_TCPCommon"
			}
	},
	"ports":{
		"25":{
			"modules/smtp/nmap_enum":{
				"name":"Module_SMTP_nmapenum",
				"secure":"False"
				},
			"modules/smtp/nmap_vuln":{
				"name":"Module_SMTP_nmapvuln",
				"secure":"False"
				}
			},
		"80":{
			"modules/http/dirsearch":{
				"name":"Module_HTTP_dirsearch",
				"secure":"False"
				},
			"modules/http/nikto":{
				"name":"Module_HTTP_nikto",
				"secure":"False"
				}
			},
		"443":{
			"modules/http/dirsearch":{
				"name":"Module_HTTP_dirsearch",
				"secure":"True"
				},
			"modules/http/nikto":{
				"name":"Module_HTTP_nikto",
				"secure":"True"
				}
		},
		"445":{
			"modules/smb/smbmap":{
				"name":"Module_SMB_smbmap"
				},
			"modules/smb/enum4linux":{
				"name":"Module_SMB_enum4linux"
				},
			"modules/smb/nbtscan":{
				"name":"Module_SMB_nbtscan"
				},
			"modules/smb/nmap_enum":{
				"name":"Module_SMB_nmapenum",
				"port":"445"
				},
			"modules/smb/nmap_vuln":{
				"name":"Module_SMB_nmapvuln",
				"port":"445"
				}
		}
	},
	"generic":{
		"modules/ping":{
			"name":"Module_Ping"
			}
	}
}
