{
	"tag":"unique_name",
	"globals":{
		"target":"10.10.10.4"
		},
	"portscan":{
		"modules/portscan/udpcommon":{
			"name":"Module_SCAN_UDPCommon"
			}
	},
	"ports":{
		"25":{
			"modules/smtp/nmap_enum":{
				"name":"Module_SMTP_nmapenum",
				"port":"25"
				},
			"modules/smtp/nmap_vuln":{
				"name":"Module_SMTP_nmapvuln",
				"port":"25"
				}
		},
		"53":{
			"modules/dns/dnsrecon":{
				"name":"Module_DNS_dnsrecon"
				}
		},
		"161":{
			"modules/snmp/onesixtyone":{
				"name":"Module_SNMP_onesixtyone",
				"community":"/usr/share/seclists/Discovery/SNMP/common-snmp-community-strings-onesixtyone.txt"
				},
			"modules/snmp/nmap_nse":{
				"name":"Module_SNMP_nmapnse",
				"port":"161"
				}
		}
	},
	"generic":{
		"modules/icmp/ping":{
			"name":"Module_ICMP_Ping"
			}
	}
}
