{
	"tag":"unique_name",
	"globals":{
		"target":"10.11.1.5,10.11.1.8"
		},
	"portscan":{
		"modules/portscan/udpcommon":{
			"name":"Module_SCAN_UDPCommon"
			}
	},
	"ports":{
		"25":{
			"modules/smtp/nmap_enum":{
				"name":"Module_SMTP_nmapenum",
				"port":"25"
				},
			"modules/smtp/nmap_vuln":{
				"name":"Module_SMTP_nmapvuln",
				"port":"25"
				}
		},
		"53":{
			"modules/examples/ping":{
				"name":"Module_Ping"
				}
		},
		"161":{
			"modules/examples/ping":{
				"name":"Module_Ping"
				}
		}
	},
	"generic":{
		"modules/examples/ping":{
			"name":"Module_Ping"
			}
	}
}
