#!/bin/bash

apt install seclists
apt install python3-pip
pip3 install -r requirements.txt

chmod +x boxdetox
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ln -sf $DIR/boxdetox /usr/bin/boxdetox
