#!/bin/bash


if [ "$#" -ne 1 ]; then
	echo "./start <name>"
else
	service postgresql start

	SESSION=$1
	tmux start-server
	
	tmux has-session -t $SESSION &> /dev/null
	if [ $? != 0 ]
	then
		tmux new-session -d -s $SESSION

		#tmux new-window -t $SESSION:0 -n oscpPWN

		tmux split-window -h -t $SESSION:0
		tmux send-keys -t $SESSION:0.1 "./boxdetox logger" Enter
		tmux split-window -v -t $SESSION:0.0
		tmux send-keys -t $SESSION:0.0 "msfconsole" Enter
		tmux send-keys -t $SESSION:0.0 "use exploit/multi/handler" Enter
		sleep 1
		tmux send-keys -t $SESSION:0.1 "./boxdetox" Enter
		tmux send-keys -t $SESSION:0.1 $SESSION Enter
	fi
	tmux attach-session -d -t $SESSION
fi


